### ISSUE TITLE
Support for Bakta output from external Bakta runs

### ISSUE THREAD

**Issue by oschwengers** [weisberglab/beav#2]
Hi and thanks a lot for this new pipeline. I'm very much looking forward to trying this - looks really promising!

Just a quick idea: How about adding a parameter that accepts the Bakta output (I guess the GenBank file) from external Bakta executions? This would add a bit of extra flexibility and save runtime, especially in automated pipelines where Bakta might be executed already on its own.

Thanks again and best regards
Oliver

**Comment by alexweisberg** [comment]
Hi Oliver,

Thank you! That is a really good idea. You are right that the genbank file would provide the most flexibility, we can extract everything else from there. We will look into it!

Best,
Alex

**Comment by acarafat** [comment]
Hi Oliver,

We have implemented a new option in beav which can take a GenBank file as input. Please check the latest release of **beav v1.3.0**. If you use `--gbk` flag, it will use the GenBank file instead of Fasta, and will skip Bakta from the pipeline.

Thank you for the great idea!

Best,
Arafat

**Comment by oschwengers** [comment]
Wonderful! I'm looking forward to give it a try. 

Thanks and best regards
Oliver
